FROM ubuntu:16.04

# make work directory at first.
WORKDIR /add
#RUN mkdir ./files && touch files/not_archived_file

# add normal file.
ADD ./files/not_archived_file .
RUN ls -al /add

# add remote resource to container.
ADD https://github.com/docker/docker-ce/blob/master/README.md .
RUN ls -al /add

# uncompress and unarchive tar files.
ADD ./training/files/tar_bzip2_file.tar.bzip2 ./training/files/tar_file.tar ./training/files/tar_file.tar ./training/files/tar_gz_file.tar.gz ./training/files/tar_xz_file.tar.xz ./
RUN ls -al /add

# not unarchive compressed files.
ADD ./training/files/bzip2_file.bz2 ./training/files/gzip_file.gz ./training/files/xz_file.xz ./training/files/zip_file.zip ./
RUN ls -al /add

# add directory.
ADD ./training/files ./training/files
RUN ls -al /add/files
