FROM busybox AS build_env

# Make work directory at first.
WORKDIR /multistage

# Copy.
COPY ./training/files/multi_stage_docker_file .
RUN ls -al /multistage

# Second docker definition.
FROM ubuntu:16.04

# Make work directory at first.
WORKDIR /copy

# Copy normal file.
COPY ./training/files/not_archived_file .
RUN ls -al /copy

# Copy normal file.
COPY --from=build_env /multistage/multi_stage_docker_file .
RUN ls -al /copy

# NOT Uncompress and unarchive tar files.
COPY ./training/files/tar_bzip2_file.tar.bzip2 ./training/files/tar_file.tar ./training/files/tar_file.tar ./training/files/tar_gz_file.tar.gz ./training/files/tar_xz_file.tar.xz ./
RUN ls -al /copy

# Copy directory.
COPY ./training/files ./training/files
RUN ls -al /copy/files
